### ISSUE TITLE
Additional dependencies for OSSC

### ISSUE THREAD

**Issue by f-hafner** [varunsatish/llama-recipes-fertility#18]
For the record, I'm putting down here how we installed the repo on the OSSC. We can update the readme or add some docs, as you see fit.

#### Additional dependencies
in the requirements.txt file that is sent to SURf, add the following:

```bash
editables==0.3.0
hatchling==1.25.0
hatch-requirements-txt==0.4.1
```

#### Install on OSSC

Ask SURF 
- to install the venv with the requirements.txt file
- to put all wheelfiles in a certain place, indicated by `WHEELPATH` below

Then, on the OSSC do
```
WHEELPATH="/gpfs/ostor/ossc9469/homedir/venvs/pmt/cruijff/wheelfiles_cruijff/" 
cd ~
module load 2023
Python/3.11.3-GCCcore-12.3.0 
source venvs/pmt/cruijff/bin/activate
cd PreFer/pmt/repositories/llama-recipes
pip install -e ./ --no-index --find-links $WHEELPATH
```

**Comment by varunsatish** [comment]
Thanks Flavio, so just to clarify--those packages have now been uploaded in our environment, I just need to adjust our requirements.txt?

I will upload the README now!

**Comment by f-hafner** [comment]
Yes, they are on the OSSC already, but it's good to keep track of them in the requirements.txt.

**Comment by varunsatish** [comment]
Perfect, I'm updating it now. Thanks :)
