### ISSUE TITLE
File paths, permissions and disk space on OSSC/Snellius 

### ISSUE THREAD

**Issue by f-hafner** [varunsatish/llama-recipes-fertility#21]
#### Disk space

Because of external constraints, you may need to be a bit economical in your data usage. 
- on public Snellius, there is a total of 3TB disk space, which you need to share with (probably) one other team
- on OSSC, there is a total of 7TB disk space, which you also need to share with one other team

#### File paths / permissions

On the OSSC, `$HOME` is `/gpfs/ostor/ossc9469/homedir/`. 
Your team's stuff is in `$HOME/PreFer/pmt/`, with 2 subdirectories
- `data/`: any data you want us to upload will be put there
- `repositories/`: all code will be put there

On public Snellius, your team has a folder `/gpfs/work3/0/prjs1058/teams/pmt/`. Inside `pmt/`, all of your team's snellius accounts should have read, write and execute permissions on any files/directories created in the  future. You can confirm this by creating some files and having other users change them. Let me know if this does not work. 

@maltelueken, fyi

**Comment by msalganik** [comment]
Moved this over to our new repo.  Closing now.
